import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
//import Image from 'next/image';
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T3 App on Clever Cloud</title> 
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
          <span className={styles.redSpan}>T3</span> App deployed on <span className={styles.blueSpan}>Clever Cloud</span>
            </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>First Steps →</h3>
              <div className={styles.cardText}>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>

            <Link
              className={styles.card}
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Documentation →</h3>
              <div className={styles.cardText}>
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>

            <Link
              className={styles.card}
              href="https://www.clever-cloud.com"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Deploy your app →</h3>
              <div className={styles.cardText}>
                Deploy your app on Clever Cloud. 
              </div>
            </Link>

            <Link
              className={styles.card}
              href="https://heptapod.host/tam-shenanigans/t3-app"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>See the code →</h3>
              <div className={styles.cardText}>
                See the code on Heptapod, our self-hosted GitLab instance. 
              </div>
            </Link>
            </div>  
        </div>
      </main>
    </>
  );
};

export default Home;
